pipelines:
  setup:
    - task: add-remote-houou
    - task: add-remote-yakuman
    - task: .env
    - task: build
    - task: dbreset

contexts:
  houou:
    executable:
      bin: docker
      args: ["compose", "run", "--rm", "houou"]

  houou-test:
    executable:
      bin: docker
      args: ["compose", "run", "-e", "RAILS_ENV=test", "--rm", "houou"]

  yakuman:
    executable:
      bin: docker
      args: ["compose", "run", "--rm", "yakuman"]

  houou-with-postgres:
    executable:
      bin: docker
      args: ["compose", "run", "--rm", "houou"]
    up: docker compose up -d postgres

tasks:
  add-remote-houou:
    description: "Add git remote for fidops/houou"
    command: git remote add houou git@github.com:fidops/houou.git

  add-remote-yakuman:
    description: "Add git remote for fidops/yakuman"
    command: git remote add yakuman git@github.com:fidops/yakuman.git

  .env:
    description: "Create .env from .env.sample"
    command: cp .env.sample .env

  build:
    description: "Build develop image for docker compose"
    command: docker compose build

  bundle:
    description: "Run bundle install manually"
    context: houou
    command: bundle install

  yarn:
    description: "Run yarn manually"
    context: yakuman
    command: yarn

  dbreset:
    description: "Repeatable DB initialization for development"
    context: houou-with-postgres
    command: bundle exec rails db:reset

  dbmigrate:
    description: "Run rails db:migrate"
    context: houou-with-postgres
    command: bundle exec rails db:migrate

  rspec:
    description: "Run RSpec"
    context: houou-test
    before: bundle exec rails db:setup
    command: bundle exec rspec

  push-to-houou:
    description: "Push to fidops/houou"
    command: git subtree push --prefix=houou houou {{index .ArgsList 0}}

  push-to-yakuman:
    description: "Push to fidops/yakuman"
    command: git subtree push --prefix=yakuman yakuman {{index .ArgsList 0}}

  pull:
    description: "Pull subtree updates"
    command:
      - git subtree pull --prefix=houou --squash houou main
      - git subtree pull --prefix=yakuman --squash yakuman main
